version: '3.8'

services:
  test-postgres:
    image: postgres:14.5-alpine
    restart: always 
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test-db
    ports:
      - '5456:5432'
    volumes:
      - ./test-db:/var/lib/postgresql/data
