const stationsInSnakeCaseWithSetDatabaseId = [
  {
    id: 1,
    stationId: '501',
    nameInFinnish: 'Hanasaari',
    nameInSwedish: 'Hanaholmen',
    nameInEnglish: 'Hanasaari',
    addressInFinnish: 'Hanasaarenranta 1',
    addressInSwedish: 'Hanaholmsstranden 1',
    cityInFinnish: 'Espoo',
    cityInSwedish: 'Esbo',
    operator: 'CityBike Finland',
    capacity: 10,
    yCoordinate: 24.840319,
    xCoordinate: 60.16582,
  },
  {
    id: 2,
    stationId: '529',
    nameInFinnish: 'Keilaniemi (M)',
    nameInSwedish: 'Kägeludden (M)',
    nameInEnglish: 'Keilaniemi (M)',
    addressInFinnish: 'Keilaniementie 4',
    addressInSwedish: 'Kägeluddsvägen 4',
    cityInFinnish: 'Espoo',
    cityInSwedish: 'Esbo',
    operator: 'CityBike Finland',
    capacity: 40,
    xCoordinate: 24.82895,
    yCoordinate: 60.175233,
  },
  {
    id: 3,
    stationId: '531',
    nameInFinnish: 'Keilaranta',
    nameInSwedish: 'Kägelstranden',
    nameInEnglish: 'Keilaranta',
    addressInFinnish: 'Keilaranta 13',
    addressInSwedish: 'Kägelstranden 13',
    cityInFinnish: 'Espoo',
    cityInSwedish: 'Esbo',
    operator: 'CityBike Finland',
    capacity: 24,
    xCoordinate: 24.835132,
    yCoordinate: 60.178762,
  },
  {
    id: 4,
    stationId: '539',
    nameInFinnish: 'Aalto-yliopisto (M), Tietot',
    nameInSwedish: 'Aalto-universitetet (M),',
    nameInEnglish: 'Aalto University (M), Tietotie',
    addressInFinnish: 'Tietotie 4',
    addressInSwedish: 'Datavägen 4',
    cityInFinnish: 'Espoo',
    cityInSwedish: 'Esbo',
    operator: 'CityBike Finland',
    capacity: 20,
    xCoordinate: 24.820099,
    yCoordinate: 60.184987,
  },
  {
    id: 5,
    stationId: '635',
    nameInFinnish: 'Kuunkatu',
    nameInSwedish: 'Mångatan',
    nameInEnglish: 'Kuunkatu',
    addressInFinnish: 'Kuunkatu 3',
    addressInSwedish: 'Mångatan 3',
    cityInFinnish: 'Espoo',
    cityInSwedish: 'Esbo',
    operator: 'CityBike Finland',
    capacity: 24,
    xCoordinate: 24.726025,
    yCoordinate: 60.172673,
  },
  {
    id: 6,
    stationId: '032',
    nameInFinnish: 'Eläinmuseo',
    nameInSwedish: 'Naturhistoriska museet',
    nameInEnglish: 'Finnish Museum of Natural History',
    addressInFinnish: 'Pohjoinen Rautatiekatu 13',
    addressInSwedish: 'Norra Järnvägsgatan 13',
    cityInFinnish: '',
    cityInSwedish: '',
    operator: '',
    capacity: 20,
    xCoordinate: 24.9318975121431,
    yCoordinate: 60.1713588986588,
  },
  {
    id: 7,
    stationId: '040',
    nameInFinnish: 'Hakaniemi (M)',
    nameInSwedish: 'Hagnäs (M)',
    nameInEnglish: 'Hakaniemi (M)',
    addressInFinnish: 'John Stenberginranta 6',
    addressInSwedish: 'John Stenbergs strand 6',
    cityInFinnish: '',
    cityInSwedish: '',
    operator: '',
    capacity: 28,
    xCoordinate: 24.9522579797678,
    yCoordinate: 60.1780816347447,
  },
  {
    id: 8,
    stationId: '108',
    nameInFinnish: 'Radiokatu',
    nameInSwedish: 'Radiogatan',
    nameInEnglish: 'Radiokatu',
    addressInFinnish: 'Kuuluttajankatu 2',
    addressInSwedish: 'Hallåmansgatan 2',
    cityInFinnish: '',
    cityInSwedish: '',
    operator: '',
    capacity: 12,
    xCoordinate: 24.9182184498931,
    yCoordinate: 60.2050064264488,
  },
  {
    id: 9,
    stationId: '204',
    nameInFinnish: 'A.I. Virtasen aukio',
    nameInSwedish: 'A. I. Virtanens plats',
    nameInEnglish: 'A.I. Virtasen aukio',
    addressInFinnish: 'Gustaf Hällströmin katu 1',
    addressInSwedish: 'Gustaf Hällströms gata 1',
    cityInFinnish: '',
    cityInSwedish: '',
    operator: '',
    capacity: 24,
    xCoordinate: 24.9620788508104,
    yCoordinate: 60.2055418168461,
  },
  {
    id: 10,
    stationId: '395',
    nameInFinnish: 'Honkasuo',
    nameInSwedish: 'Hongasmossa',
    nameInEnglish: 'Honkasuo',
    addressInFinnish: 'Naapuripellontie 27',
    addressInSwedish: 'Naboängsvägen 27',
    cityInFinnish: '',
    cityInSwedish: '',
    operator: '',
    capacity: 16,
    xCoordinate: 24.8465809743929,
    yCoordinate: 60.255557476007,
  },
]

export { stationsInSnakeCaseWithSetDatabaseId }
