const stationsInSnakeCaseWithSetDatabaseId = [
  {
    id: 1,
    station_id: '501',
    name_in_finnish: 'Hanasaari',
    name_in_swedish: 'Hanaholmen',
    name_in_english: 'Hanasaari',
    address_in_finnish: 'Hanasaarenranta 1',
    address_in_swedish: 'Hanaholmsstranden 1',
    city_in_finnish: 'Espoo',
    city_in_swedish: 'Esbo',
    operator: 'CityBike Finland',
    capacity: 10,
    y_coordinate: 24.840319,
    x_coordinate: 60.16582,
  },
  {
    id: 2,
    station_id: '529',
    name_in_finnish: 'Keilaniemi (M)',
    name_in_swedish: 'Kägeludden (M)',
    name_in_english: 'Keilaniemi (M)',
    address_in_finnish: 'Keilaniementie 4',
    address_in_swedish: 'Kägeluddsvägen 4',
    city_in_finnish: 'Espoo',
    city_in_swedish: 'Esbo',
    operator: 'CityBike Finland',
    capacity: 40,
    x_coordinate: 24.82895,
    y_coordinate: 60.175233,
  },
  {
    id: 3,
    station_id: '531',
    name_in_finnish: 'Keilaranta',
    name_in_swedish: 'Kägelstranden',
    name_in_english: 'Keilaranta',
    address_in_finnish: 'Keilaranta 13',
    address_in_swedish: 'Kägelstranden 13',
    city_in_finnish: 'Espoo',
    city_in_swedish: 'Esbo',
    operator: 'CityBike Finland',
    capacity: 24,
    x_coordinate: 24.835132,
    y_coordinate: 60.178762,
  },
  {
    id: 4,
    station_id: '539',
    name_in_finnish: 'Aalto-yliopisto (M), Tietot',
    name_in_swedish: 'Aalto-universitetet (M),',
    name_in_english: 'Aalto University (M), Tietotie',
    address_in_finnish: 'Tietotie 4',
    address_in_swedish: 'Datavägen 4',
    city_in_finnish: 'Espoo',
    city_in_swedish: 'Esbo',
    operator: 'CityBike Finland',
    capacity: 20,
    x_coordinate: 24.820099,
    y_coordinate: 60.184987,
  },
  {
    id: 5,
    station_id: '635',
    name_in_finnish: 'Kuunkatu',
    name_in_swedish: 'Mångatan',
    name_in_english: 'Kuunkatu',
    address_in_finnish: 'Kuunkatu 3',
    address_in_swedish: 'Mångatan 3',
    city_in_finnish: 'Espoo',
    city_in_swedish: 'Esbo',
    operator: 'CityBike Finland',
    capacity: 24,
    x_coordinate: 24.726025,
    y_coordinate: 60.172673,
  },
  {
    id: 6,
    station_id: '032',
    name_in_finnish: 'Eläinmuseo',
    name_in_swedish: 'Naturhistoriska museet',
    name_in_english: 'Finnish Museum of Natural History',
    address_in_finnish: 'Pohjoinen Rautatiekatu 13',
    address_in_swedish: 'Norra Järnvägsgatan 13',
    city_in_finnish: '',
    city_in_swedish: '',
    operator: '',
    capacity: 20,
    x_coordinate: 24.9318975121431,
    y_coordinate: 60.1713588986588,
  },
  {
    id: 7,
    station_id: '040',
    name_in_finnish: 'Hakaniemi (M)',
    name_in_swedish: 'Hagnäs (M)',
    name_in_english: 'Hakaniemi (M)',
    address_in_finnish: 'John Stenberginranta 6',
    address_in_swedish: 'John Stenbergs strand 6',
    city_in_finnish: '',
    city_in_swedish: '',
    operator: '',
    capacity: 28,
    x_coordinate: 24.9522579797678,
    y_coordinate: 60.1780816347447,
  },
  {
    id: 8,
    station_id: '108',
    name_in_finnish: 'Radiokatu',
    name_in_swedish: 'Radiogatan',
    name_in_english: 'Radiokatu',
    address_in_finnish: 'Kuuluttajankatu 2',
    address_in_swedish: 'Hallåmansgatan 2',
    city_in_finnish: '',
    city_in_swedish: '',
    operator: '',
    capacity: 12,
    x_coordinate: 24.9182184498931,
    y_coordinate: 60.2050064264488,
  },
  {
    id: 9,
    station_id: '204',
    name_in_finnish: 'A.I. Virtasen aukio',
    name_in_swedish: 'A. I. Virtanens plats',
    name_in_english: 'A.I. Virtasen aukio',
    address_in_finnish: 'Gustaf Hällströmin katu 1',
    address_in_swedish: 'Gustaf Hällströms gata 1',
    city_in_finnish: '',
    city_in_swedish: '',
    operator: '',
    capacity: 24,
    x_coordinate: 24.9620788508104,
    y_coordinate: 60.2055418168461,
  },
  {
    id: 10,
    station_id: '395',
    name_in_finnish: 'Honkasuo',
    name_in_swedish: 'Hongasmossa',
    name_in_english: 'Honkasuo',
    address_in_finnish: 'Naapuripellontie 27',
    address_in_swedish: 'Naboängsvägen 27',
    city_in_finnish: '',
    city_in_swedish: '',
    operator: '',
    capacity: 16,
    x_coordinate: 24.8465809743929,
    y_coordinate: 60.255557476007,
  },
]

const getLastIdOfStations = () => {
  const lastStation = stationsInSnakeCaseWithSetDatabaseId.length - 1
  const lastStationEntry = stationsInSnakeCaseWithSetDatabaseId[lastStation]
  return lastStationEntry.id
}

module.exports = {
  stationsInSnakeCaseWithSetDatabaseId,
  getLastIdOfStations,
}
